---
title: "Asset Correlations"
output: html_notebook
---

```{r}
library(purrr)
library(tibble)
library(dplyr)

# List of tickers for sector etfs. 
# Omit XLRE because its inception is 2015. Not really enough to check out long term monthly correlations. 

ticker <- c("XLY", "XLP", "XLE",	"XLF", "XLV",	
             "XLI", "XLB", "XLK", "XLU", "SPY")	

# And the accompanying sector names for those ETFs.

sector <- c("Consumer Discretionary", "Consumer Staples", 
             "Energy", "Financials", "Health Care", "Industrials", 
             "Materials", "Technology", "Utilities", "Index")

etf_ticker_sector <- data_frame(ticker, sector) %>% as_tibble()

```

```{r}

# A function to pull in stock prices and build a tibble.

monthly_stock_prices <- function(ticker, start_year) {
    
    # Get stock prices. Have a look at this previous post for more on getSymbols.
    prices <- getSymbols(Symbols = ticker, from = start_year, auto.assign = FALSE)

    # Rename the columns to something generic so we can select on it, else
    # it will include the ticker name and make the selection dependent on the
    # ticker. I use nonsense names for the first four because we are going
    # to abandon them. 
    
    names(prices) <- c("a", "b", "c", "d", "e", "Adjusted")
    
    # Construct our final tibble. We need to convert the 
    # xts object to a tibble, then add a 'Date' column using 
    # the lubridate package and ymd() function.
    
    prices <- prices %>%
            as_tibble() %>% 
            select(Adjusted) %>% 
            rownames_to_column(var = "Date") %>%
            mutate(Date = ymd(Date))
    
    prices
}

```

```{r}
# A function to take the stock prices and calculate monthly returns.

monthly_stock_returns <- function(prices) {
    
    # We are passing in the tibble from the previous function, so first let's 
    # convert to xts.
  
    prices <- xts(prices[, -1], order.by = prices$Date)
    
    # Get log returns. This should look familiar from the previous post as well.
    
    returns <- periodReturn(x = prices$Adjusted, type = 'log', period = 'monthly')
    
    # Rename the column returns so we don't get confused later.
    names(returns) <- "returns"
    
    returns <- returns %>%
            as_tibble() %>%
            rownames_to_column(var = "Date") %>%
            mutate(Date = ymd(Date)) 
        
    returns
}
```

```{r}
# Let's take our tibble of etf tickers and sectors and pass it to our two functions. 
# We'll pull in the price data and the returns data, but I want just the returns
# so we'll exclude the prices when we run select().

etf_test <- etf_ticker_sector %>%
    mutate(prices = map(ticker, function(.x) monthly_stock_prices(.x, "2006-10-01"))) %>% 
    mutate(returns  = map(prices, function(.x) monthly_stock_returns(.x))) %>% 
    select(ticker, sector, returns) 

```


```{r}
# A function that calculates the rolling correlation between a sector and the SPY index. 
# For a sanity check, you can pass in the SPY tibble and make sure it returns 1's.

sector_index_correlation <- function(sector_returns, window) {
  
    sector_xts <- xts(sector_returns[,-1], order.by = sector_returns$Date)
    spy_xts <- xts(etf_test$returns[[10]][,-1], order.by = etf_test$returns[[10]]$Date)
    merged_xts <- merge(sector_xts, spy_xts)

    merged_xts$rolling_test <- rollapply(merged_xts, window, 
                                         function(x) cor(x[,1], x[,2], use="pairwise.complete.obs"), 
                                         by.column = FALSE)
    
    names(merged_xts) <- c("Sector Returns", "SPY Returns", "Sector/SPY Correlation")
    
    merged_xts
}

# Choose a sector ETF and a rolling window. 
# I will go with a 20 month window and the Information Technology sector.

sector_correlation <- sector_index_correlation(etf_test$returns[[8]], 20)

```

```{r}
# Let's graph the sector/index rolling correlation using our old friend dygraphs. 
# I'll add an event for the financial crisis and shade the recession of 2007-2009 with 
# an unimposing pinkish.

dygraph(sector_correlation$'Sector/SPY Correlation', main = "Correlation between SP500 and Sector ETF X") %>% 
    dyAxis("y", label = "Correlation") %>% 
    dyRangeSelector(height = 20) %>%
    dyShading(from = "2007-12-01", to = "2009-06-01", color = "#FFE6E6") %>% 
    dyEvent(x = "2008-09-15", label = "Fin Crisis", labelLoc = "top", color = "red") %>% 
    dyOptions(colors = RColorBrewer::brewer.pal(3, "Set2"))
```



